spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clinic}
    username: ${SPRING_DATASOURCE_USERNAME:clinic}
    password: ${SPRING_DATASOURCE_PASSWORD:clinic}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: true
  thymeleaf:
    cache: false

server:
  port: 8080